import { Product, DEFAULT_COLORS } from "./types";

const SIZES_STANDARD = [46, 48, 50, 52, 54, 56];

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "medical-beige-vneck",
    name: "Комплект «Аврора» бежевый",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Женский медицинский комплект с V-образным вырезом и рукавом 3/4. Лёгкая, дышащая ткань держит форму весь день.",
    material: "Смесовая ткань (67% полиэстер, 33% хлопок), плотность 190 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-w-beige-vneck-1.jpg", "/products/med-w-beige-vneck-2.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: Date.now() - 1000,
  },
  {
    id: "p2",
    slug: "medical-teal-classic",
    name: "Комплект «Лагуна» изумрудный",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Насыщенный изумрудный оттенок для тех, кто хочет выделиться в отделении. Свободный крой, накладные карманы на кнопках.",
    material: "Смесовая ткань (67% полиэстер, 33% хлопок), плотность 190 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-w-teal.jpg"],
    isNew: false,
    isBestseller: true,
    hidden: false,
    createdAt: Date.now() - 2000,
  },
  {
    id: "p3",
    slug: "medical-gray-zip-male",
    name: "Костюм «Форт» серый",
    price: 1700,
    category: "medical",
    gender: "male",
    description:
      "Мужской костюм на молнии с контрастной отделкой. Усиленные карманы-карго на брюках для инструментов и гаджетов.",
    material: "Смесовая ткань рип-стоп, плотность 210 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-m-gray-zip.jpg"],
    isNew: false,
    isBestseller: true,
    hidden: false,
    createdAt: Date.now() - 3000,
  },
  {
    id: "p4",
    slug: "medical-navy-belt",
    name: "Комплект «Династия» тёмно-синий",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Приталенный силуэт с поясом на завязке и воротником-стойкой. Премиальный вид для клиник и клиник эстетической медицины.",
    material: "Смесовая ткань (67% полиэстер, 33% хлопок), плотность 190 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-w-navy-belt.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: Date.now() - 4000,
  },
  {
    id: "p5",
    slug: "medical-red-belt",
    name: "Комплект «Флэш» красный",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Яркий акцентный цвет с воротником-стойкой и поясом. Идеально для брендированных клиник, где важна узнаваемость.",
    material: "Смесовая ткань (67% полиэстер, 33% хлопок), плотность 190 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-w-red-belt.jpg"],
    isNew: false,
    isBestseller: false,
    hidden: false,
    createdAt: Date.now() - 5000,
  },
  {
    id: "p6",
    slug: "medical-navy-zip-male",
    name: "Костюм «Аргон» тёмно-синий",
    price: 1700,
    category: "medical",
    gender: "male",
    description:
      "Мужской комплект на молнии свободного кроя с коротким рукавом. Устойчив к частым стиркам, не теряет цвет.",
    material: "Смесовая ткань рип-стоп, плотность 210 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-m-navy-zip.jpg"],
    isNew: false,
    isBestseller: false,
    hidden: false,
    createdAt: Date.now() - 6000,
  },
  {
    id: "p7",
    slug: "medical-white-belt",
    name: "Комплект «Люмен» белый",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Классический белый с воротником-стойкой и завязкой на талии. Строгий премиальный образ для стоматологий и клиник.",
    material: "Плотный хлопок с сатиновой отделкой, 200 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-w-white-belt.jpg"],
    isNew: false,
    isBestseller: true,
    hidden: false,
    createdAt: Date.now() - 7000,
  },
  {
    id: "p8",
    slug: "medical-olive-vneck",
    name: "Комплект «Олива» хаки",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Спокойный оливковый оттенок, V-образный вырез, рукав 3/4. Хорошо сочетается с любой цветовой палитрой клиники.",
    material: "Смесовая ткань (67% полиэстер, 33% хлопок), плотность 190 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-w-olive-vneck.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: Date.now() - 8000,
  },
  {
    id: "p9",
    slug: "medical-green-wrap",
    name: "Комплект «Оазис» запах зелёный",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Асимметричный крой на запах с боковой завязкой — женственный силуэт для косметологов и терапевтов.",
    material: "Смесовая ткань (67% полиэстер, 33% хлопок), плотность 190 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-w-green-wrap.jpg"],
    isNew: false,
    isBestseller: false,
    hidden: false,
    createdAt: Date.now() - 9000,
  },
  {
    id: "p10",
    slug: "medical-navy-wrap",
    name: "Комплект «Оазис» запах тёмно-синий",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Тот же силуэт на запах в тёмно-синем цвете — универсальный вариант для любой клиники.",
    material: "Смесовая ткань (67% полиэстер, 33% хлопок), плотность 190 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/med-w-navy-wrap.jpg"],
    isNew: false,
    isBestseller: false,
    hidden: false,
    createdAt: Date.now() - 10000,
  },
  {
    id: "p11",
    slug: "chef-jacket-female",
    name: "Куртка повара «Бригад» женская",
    price: 1700,
    category: "chef",
    gender: "female",
    description:
      "Женская поварская куртка с двубортной застёжкой, воздухопроницаемая, легко отстирывается от пятен.",
    material: "Плотный хлопок с тефлоновой пропиткой, 220 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/chef-w-jacket.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: Date.now() - 11000,
  },
  {
    id: "p12",
    slug: "chef-jacket-male",
    name: "Куртка повара «Бригад» мужская",
    price: 1700,
    category: "chef",
    gender: "male",
    description:
      "Мужская поварская куртка классического кроя с длинным рукавом, укреплённые швы для интенсивной кухонной работы.",
    material: "Плотный хлопок с тефлоновой пропиткой, 220 г/м²",
    sizes: SIZES_STANDARD,
    colors: DEFAULT_COLORS,
    images: ["/products/chef-m-jacket.jpg"],
    isNew: false,
    isBestseller: true,
    hidden: false,
    createdAt: Date.now() - 12000,
  },
];
