import { Product, DEFAULT_COLORS } from "./types";

function sizeRange(from: number, to: number): number[] {
  const out: number[] = [];
  for (let s = from; s <= to; s += 2) out.push(s);
  return out;
}

let counter = 0;
const now = Date.now();
function nextCreatedAt() {
  counter += 1;
  return now - counter * 1000;
}

export const SEED_PRODUCTS: Product[] = [
  {
    id: "linda",
    slug: "linda",
    name: "Linda",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Женский медицинский костюм «Linda» — свободный крой из ткани TR Панацея, приятной к телу и комфортной на всю смену.",
    material: "TR Панацея",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: [
      "/products/linda/1.jpg", "/products/linda/2.jpg", "/products/linda/3.jpg",
      "/products/linda/4.jpg", "/products/linda/5.jpg", "/products/linda/6.jpg",
      "/products/linda/7.jpg", "/products/linda/8.jpg", "/products/linda/9.jpg",
      "/products/linda/10.jpg", "/products/linda/11.jpg", "/products/linda/12.jpg",
      "/products/linda/13.jpg",
    ],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "seryy-tugma",
    slug: "seryy-tugma",
    name: "Серый тугма",
    price: 1700,
    category: "medical",
    gender: "male",
    description:
      "Мужской медицинский халат «Серый тугма» — практичный прямой крой на пуговицах из плотной ткани TC Джинсовый.",
    material: "TC Джинсовый",
    sizes: sizeRange(44, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/seryy-tugma/1.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "belbogli",
    slug: "belbogli",
    name: "Белбогли",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Женский медицинский костюм «Белбогли» с поясом на завязке — приталенный силуэт из ткани TC Джинсовый.",
    material: "TC Джинсовый",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/belbogli/1.jpg", "/products/belbogli/2.jpg", "/products/belbogli/3.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "madena-zamok",
    slug: "madena-zamok",
    name: "Мадена замок",
    price: 1700,
    category: "medical",
    gender: "male",
    description:
      "Мужской медицинский костюм «Мадена замок» на молнии — удобная посадка из ткани TC Джинсовый.",
    material: "TC Джинсовый",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/madena-zamok/1.jpg", "/products/madena-zamok/2.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "viktoriya",
    slug: "viktoriya",
    name: "Виктория",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Женский медицинский костюм «Виктория» — универсальная модель из плотной ткани TC Strong Overflow, держит форму весь день.",
    material: "TC Strong Overflow",
    sizes: sizeRange(48, 58),
    colors: DEFAULT_COLORS,
    images: [
      "/products/viktoriya/1.jpg", "/products/viktoriya/2.jpg", "/products/viktoriya/3.jpg",
      "/products/viktoriya/4.jpg", "/products/viktoriya/5.jpg", "/products/viktoriya/6.jpg",
      "/products/viktoriya/7.jpg",
    ],
    isNew: true,
    isBestseller: true,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "miranda",
    slug: "miranda",
    name: "Миранда",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Женский медицинский костюм «Миранда» — аккуратный крой из ткани TC Джинсовый на каждый день.",
    material: "TC Джинсовый",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/miranda/1.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "stoyka-zhen",
    slug: "stoyka-zhen",
    name: "Стойка",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Женский медицинский халат «Стойка» с воротником-стойкой — эластичная посадка из спандекса, приятная к телу.",
    material: "Спандекс (эластичная)",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/stoyka-zhen/1.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "halat-10",
    slug: "halat-10",
    name: "Халат-10",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Женский медицинский халат «Халат-10» классического прямого кроя из ткани TC — универсальный вариант на каждый день.",
    material: "TC",
    sizes: sizeRange(48, 60),
    colors: DEFAULT_COLORS,
    images: ["/products/halat-10/1.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "asia-sun-print",
    slug: "asia-sun-print",
    name: "Asia Sun Print",
    price: 1700,
    category: "medical",
    gender: "unisex",
    description:
      "Медицинский костюм «Asia Sun Print» с ярким принтом — лёгкая ткань TC Flexy, подходит и мужчинам, и женщинам.",
    material: "TC Flexy",
    sizes: sizeRange(44, 58),
    colors: DEFAULT_COLORS,
    images: ["/products/asia-sun-print/1.jpg", "/products/asia-sun-print/2.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "shaxodat",
    slug: "shaxodat",
    name: "Shaxodat",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Женский медицинский костюм «Shaxodat» — облегающий силуэт из эластичного спандекса, свободный в движении.",
    material: "Спандекс (эластичная)",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/shaxodat/1.jpg", "/products/shaxodat/2.jpg"],
    isNew: true,
    isBestseller: true,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "maks",
    slug: "maks",
    name: "Макс",
    price: 1700,
    category: "medical",
    gender: "male",
    description:
      "Мужской медицинский халат «Макс» прямого кроя из ткани TC — практичная и неприхотливая в уходе модель.",
    material: "TC",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/maks/1.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "agata",
    slug: "agata",
    name: "Агата",
    price: 1700,
    category: "medical",
    gender: "female",
    description:
      "Женский медицинский халат «Агата» из ткани TC — сдержанная классика для клиник и кабинетов.",
    material: "TC",
    sizes: sizeRange(46, 60),
    colors: DEFAULT_COLORS,
    images: ["/products/agata/1.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "viktor",
    slug: "viktor",
    name: "Виктор",
    price: 1700,
    category: "medical",
    gender: "male",
    description:
      "Мужской медицинский халат «Виктор» из ткани TC — сдержанный крой для клиник и стационаров.",
    material: "TC",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/viktor/1.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "stoyka-muzh",
    slug: "stoyka-muzh",
    name: "Стойка",
    price: 1700,
    category: "medical",
    gender: "male",
    description:
      "Мужской медицинский халат «Стойка» с воротником-стойкой из ткани TC. Фото модели ещё не загружено — товар скрыт из каталога до добавления реального фото.",
    material: "TC",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/stoyka-muzh/1.jpg"],
    isNew: true,
    isBestseller: false,
    hidden: true,
    createdAt: nextCreatedAt(),
  },
  {
    id: "chef-w",
    slug: "chef-jacket-female",
    name: "Куртка повара «Бригад» женская",
    price: 1700,
    category: "chef",
    gender: "female",
    description:
      "Женская поварская куртка с двубортной застёжкой, воздухопроницаемая, легко отстирывается от пятен.",
    material: "Плотный хлопок с тефлоновой пропиткой",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/chef-w-jacket.jpg"],
    isNew: false,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
  {
    id: "chef-m",
    slug: "chef-jacket-male",
    name: "Куртка повара «Бригад» мужская",
    price: 1700,
    category: "chef",
    gender: "male",
    description:
      "Мужская поварская куртка классического кроя с длинным рукавом, укреплённые швы для интенсивной кухонной работы.",
    material: "Плотный хлопок с тефлоновой пропиткой",
    sizes: sizeRange(46, 56),
    colors: DEFAULT_COLORS,
    images: ["/products/chef-m-jacket.jpg"],
    isNew: false,
    isBestseller: false,
    hidden: false,
    createdAt: nextCreatedAt(),
  },
];
